version: "3.7"
services:
  db:
    image: "postgres:11.5"
    env_file: ./.env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
