name: Rails Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          POSTGRES_PASSWORD: password

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7.5
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.5
        bundler-cache: true
    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: '14.14.0'
        cache: 'yarn'
    - name: Install npm dependencies
      run: yarn install
    - name: Build
      env:
        PGHOST: 127.0.0.1
        PGUSER: postgres
        POSTGRES_PASSWORD: password
      run: |
        sudo apt-get -yqq install libpq-dev
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rails webpacker:compile
    - name: Run Specs
      run: |
        bundle exec rspec
