name: Rails Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          POSTGRES_PASSWORD: password

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - name: Cache ruby gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install npm dependencies
      run: |
        npm i -g yarn
        yarn
    - name: Build
      env:
        PGHOST: 127.0.0.1
        PGUSER: postgres
        POSTGRES_PASSWORD: password
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rails webpacker:compile
    - name: Run Specs
      run: |
        bundle exec rspec
